default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Kairos_development

test:
  <<: *default
  database: Kairos_test

# production:
#   <<: *default
#   database: Kairos_production
#   username: Kairos
#   password: <%= ENV['KAIROS_DATABASE_PASSWORD'] %>


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: Kairos_production
  username: Kairos
  password: <%= ENV['KAIROS_DATABASE_PASSWORD'] %>
